### ISSUE TITLE
Safe navigation operator only available in Ruby 2.3

### ISSUE THREAD

**Issue by severin** [saharaying/graphql-result_cache#1]
Hi there,

I noticed a tiny issue with your gem: The code uses the safe navigation operator (`&.`) in some places. This feature was only introduced in Ruby 2.3. However, your gemspec file specifies that the gem works with Ruby 2.1 and newer.

(I noticed it because I'm unfortunately stuck on a 2.2 codebase and wanted to try your gem)

**Comment by saharaying** [comment]
@severin Fixed in v0.1.4. Now you can have a try.

**Comment by severin** [comment]
@saharaying thanks a lot! Will have a look soon!
